//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSessions
    {
        public int SessionID { get; set; }
        public int CourseID { get; set; }
        public int DayOfWeek { get; set; }
        public int StartPeriod { get; set; }
        public int EndPeriod { get; set; }
        public string Classroom { get; set; }
        public int StartWeek { get; set; }
        public int EndWeek { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
