//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exams
    {
        public int ExamID { get; set; }
        public int CourseID { get; set; }
        [Display(Name = "考试时间")]
        public System.DateTime ExamTime { get; set; }
        [Display(Name = "考试地点")]
        public string Location { get; set; }
        [Display(Name = "备注")]
        public string Details { get; set; }

        public virtual Courses Courses { get; set; }
    }
}
