//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInformationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passkeys
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte[] CredentialId { get; set; }
        public byte[] PublicKey { get; set; }
        public byte[] UserHandle { get; set; }
        public long SignatureCounter { get; set; }
        public string CredType { get; set; }
        public System.DateTime RegDate { get; set; }
        public System.Guid AaGuid { get; set; }
        public string Name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
